/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NearImport } from './routes/near'
import { Route as BlockchainImport } from './routes/blockchain'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NearRoute = NearImport.update({
  id: '/near',
  path: '/near',
  getParentRoute: () => rootRoute,
} as any)

const BlockchainRoute = BlockchainImport.update({
  id: '/blockchain',
  path: '/blockchain',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blockchain': {
      id: '/blockchain'
      path: '/blockchain'
      fullPath: '/blockchain'
      preLoaderRoute: typeof BlockchainImport
      parentRoute: typeof rootRoute
    }
    '/near': {
      id: '/near'
      path: '/near'
      fullPath: '/near'
      preLoaderRoute: typeof NearImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blockchain': typeof BlockchainRoute
  '/near': typeof NearRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blockchain': typeof BlockchainRoute
  '/near': typeof NearRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/blockchain': typeof BlockchainRoute
  '/near': typeof NearRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blockchain' | '/near'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blockchain' | '/near'
  id: '__root__' | '/' | '/blockchain' | '/near'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockchainRoute: typeof BlockchainRoute
  NearRoute: typeof NearRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockchainRoute: BlockchainRoute,
  NearRoute: NearRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blockchain",
        "/near"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blockchain": {
      "filePath": "blockchain.tsx"
    },
    "/near": {
      "filePath": "near.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
